<%
  adapter = ENV.fetch("DB_ADAPTER") { 'postgresql' }
  encoding = (adapter == 'postgresql') ? 'unicode' : 'utf8mb4'
%>

default: &default
  encoding: <%= encoding %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") {
      "#{adapter}://rails:rails123@localhost/activity_timer_dev" } %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") {
      "#{adapter}://rails:rails123@localhost/activity_timer_test" } %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") {
      "#{adapter}://rails:rails123@localhost/activity_timer_prod" } %>
